# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. 
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters

In [1]:
import torch
import numpy as np

In [2]:
# Creating tensor from data

data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
# Creating tensor from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)



In [5]:
# Creating new tensors

#The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"random tensor \n {x_rand} \n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

random tensor 
 tensor([[0.6309, 0.0012],
        [0.3265, 0.2789]]) 



In [6]:
#With random or constant values:
#shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.8423, 0.4983, 0.8144],
        [0.1756, 0.6749, 0.4119]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# Attributes of a Tensor
#Tensor attributes describe their shape, datatype, and the device on which they are stored.

tensor = torch.rand(3,4)

print("tensor shape:", tensor.shape)
print("Tensor dtype", tensor.dtype)
print("saved where:", tensor.device)

tensor shape: torch.Size([3, 4])
Tensor dtype torch.float32
saved where: cpu


In [8]:
# Operations on Tensors
# By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability).
# Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [14]:
# Basic indexing and slicing

Tensor = torch.ones(4,4)

print(Tensor[0][0]) # first element and first column
print(Tensor[0, :]) # first row and all columns
print(Tensor[:, 1]) # all rows and 1st column
print(Tensor[..., -1]) # last column
Tensor[:, 1] = 0
print(Tensor)

tensor(1.)
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
# Joining tensors - concatinating 

t1 = torch.cat([Tensor, Tensor, Tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [16]:
# Arithmatic operations
# Matrix multiplication - y1, y2, y3 will have the same value

y1 = Tensor @ Tensor.T # transpose
y2 = Tensor.matmul(Tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(Tensor, Tensor.T, out = y3)

print(y1)


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [17]:
# This computes the element-wise product. z1, z2, z3 will have the same value

z1 = Tensor * Tensor
z2 = Tensor.mul(Tensor)
z3 = torch.rand_like(Tensor)
torch.mul(Tensor, Tensor, out = z3)

print(z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [18]:
# Single-element tensors If you have a one-element tensor, 
#for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item()

agg = Tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [19]:
# In-place operations Operations that store the result into the operand are called in-place. 
#They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x

print(f"{Tensor} \n")
Tensor.add_(5) # inplace operation 
print(f"{Tensor} \n")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 



In [20]:
# Tensor to NumPy array

t = torch.ones(5)
print(f"{t} \n")

n = t.numpy()
print(f"{n} \n")

tensor([1., 1., 1., 1., 1.]) 

[1. 1. 1. 1. 1.] 



In [21]:
# A change in the tensor reflects in the NumPy array.

t.add_(5)

print(f"{t} \n")
print(f"{n} \n")

tensor([6., 6., 6., 6., 6.]) 

[6. 6. 6. 6. 6.] 



In [22]:
# NumPy array to Tensor

n = np.ones(5)
t = torch.from_numpy(n)

print(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [24]:

n = n + 5

print(f"{t} \n")
print(f"{n} \n")

tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 

[6. 6. 6. 6. 6.] 



In [25]:
# Changes in the NumPy array reflects in the tensor
np.add(n, 1, out=n)

print(f"{t} \n")
print(f"{n} \n")

tensor([1., 1., 1., 1., 1.], dtype=torch.float64) 

[7. 7. 7. 7. 7.] 



In [26]:
n = np.ones(5)
t = torch.from_numpy(n)

In [27]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
